---
title: "Tipos de filme de FULANO(A)"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(cluster)
library(plotly)
library(ggdendro)

source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
## ANTES DE USAR
# Para criar data/movies.csv
import_data("chris_evans") 
```


```{r read}
filmes = read_imported_data()
```

## Descrição

```{r}
filmes %>% 
    ggplot(aes(x = avaliacao, y = bilheteria)) + 
    geom_point(size = 4, color = paleta[1]) 
```



```{r}
filmes %>% 
    ggplot(aes(x = bilheteria, y = avaliacao)) + 
    geom_bar(fill = paleta[2], color = "black", iden) + 
    geom_rug(size = .5) 
```

```{r}
filmes %>% 
    ggplot(aes(x = avaliacao)) + 
    geom_histogram(binwidth = 5, fill = paleta[3], color = "black") + 
    geom_rug(size = .5) 

filmes %>% 
    ggplot(aes(x = bilheteria)) + 
    geom_histogram(fill = paleta[3], color = "black") + 
    geom_rug(size = .5) 

filmes %>% 
    ggplot(aes(x = log(bilheteria))) + 
    geom_histogram(bins = 10, fill = paleta[3], color = "black") + 
    geom_rug(size = .5) 


```

## Estrutura de grupos?

```{r}
p = filmes %>% 
    ggplot(aes(x = avaliacao, y = log(bilheteria), label = filme)) + 
    geom_jitter(width = .05, alpha = .3, size = 3) + 
    labs(x = "avaliacao")

ggplotly(p)
```

## Agrupamento hierárquico

```{r}
agrupamento_h = filmes %>%  
    mutate(bilheteria = log(bilheteria)) %>% 
    mutate_at(vars(avaliacao, bilheteria), 
              funs(scale)) %>% 
    as.data.frame() %>% 
    column_to_rownames("filme") %>% 
    select(avaliacao, bilheteria) %>%
    dist(method = "euclidian") %>% 
    hclust(method = "centroid")

ggdendrogram(agrupamento_h, rotate = T, size = 2, theme_dendro = F) + 
    labs(y = "Dissimilaridade", x = "", title = "Dendrograma")

data.frame(height = agrupamento_h$height) %>% 
    mutate(k = 1:n()) %>% 
    ggplot(aes(x = k, y = height)) + 
    geom_line(colour = "grey") + 
    geom_point() + 
    labs(x = "Número de passos no algoritmo", y = "Dissimilaridade na junção")


```

```{r}
get_grupos <- function(agrupamento, num_grupos){
    agrupamento %>% 
        cutree(num_grupos) %>% 
        as.data.frame() %>% 
        mutate(label = rownames(.)) %>% 
        gather(key =  "k", value = "grupo", -label) %>% 
        mutate(grupo = as.character(grupo))
}

atribuicoes = get_grupos(agrupamento_h, num_grupos = 1:6)

atribuicoes = atribuicoes %>% 
    left_join(filmes, by = c("label" = "filme"))

atribuicoes %>% 
    ggplot(aes(x = bilheteria, y = avaliacao, colour = grupo)) + 
    geom_jitter(width = .02, height = 0, size = 1.6, alpha = .6) + 
    facet_wrap(~ paste(k, " grupos")) + 
    scale_color_brewer(palette = "Dark2")


```

```{r}
k_escolhido = 5

a <- atribuicoes %>% 
    filter(k == k_escolhido) %>% 
    ggplot(aes(x = log(bilheteria), y = avaliacao, colour = grupo)) + 
    geom_jitter(width = .02, height = 0, size = 3, alpha = .6) + 
    facet_wrap(~ paste(k, " grupos")) + 
    scale_color_brewer(palette = "Dark2") + 
    labs(x = "bilheteria", y = "Avaliação RT") + 
    coord_flip() 

ggplotly(a)
```

